Summary:	A simple library to connect Qt application with libvlc
Name:		vlc-qt
Version:	0.8.1
Release:	1
License:	LGPLv2.1+
Group:		System/Libraries
Url:		http://projects.tano.si/library
# Generated by github https://github.com/ntadej/vlc-qt
Source0:	%{name}-%{version}.tar.gz
Patch0:		vlc-qt-0.8.1-linkage.patch
# Also build pkgconfig files for QML and widgets libraries
Patch1:		vlc-qt-0.8.1-pkgconfig.patch
BuildRequires:	cmake
BuildRequires:	qt4-devel
BuildRequires:	pkgconfig(libvlc)

%description
VLC-Qt is a free library used to connect Qt and libvlc libraries.
It contains core classes for main media playback and also some GUI
classes for faster media player developement.

#----------------------------------------------------------------------------

%define libvlcqt_major 0.8
%define libvlcqt %mklibname vlc-qt %{libvlcqt_major}

%package -n %{libvlcqt}
Summary:	A simple library to connect Qt application with libvlc (core)
Group:		System/Libraries

%description -n %{libvlcqt}
VLC-Qt is a free library used to connect Qt and libvlc libraries.
It contains core classes for main media playback and also some GUI
classes for faster media player developement.

This package contains vlc-qt core library.

%files  -n %{libvlcqt}
%{_libdir}/libvlc-qt.so.%{libvlcqt_major}*

#----------------------------------------------------------------------------

%define devvlcqt %mklibname vlc-qt -d

%package -n %{devvlcqt}
Summary:	Headers and development libraries for vlc-qt core library
Group:		Development/C++
Requires:	%{libvlcqt} = %{EVRD}
Provides:	%{name}-devel = %{EVRD}

%description -n %{devvlcqt}
Headers and development libraries for vlc-qt core library.

%files  -n %{devvlcqt}
%doc AUTHORS CHANGELOG README.md LICENSE.GPL LICENSE.LGPL
%{_libdir}/pkgconfig/libvlc-qt.pc
%{_libdir}/libvlc-qt.so
%{_includedir}/%{name}/Audio.h
%{_includedir}/%{name}/Common.h
%{_includedir}/%{name}/Config.h
%{_includedir}/%{name}/Enums.h
%{_includedir}/%{name}/Error.h
%{_includedir}/%{name}/Instance.h
%{_includedir}/%{name}/Media.h
%{_includedir}/%{name}/MediaList.h
%{_includedir}/%{name}/MediaListPlayer.h
%{_includedir}/%{name}/MediaPlayer.h
%{_includedir}/%{name}/MetaManager.h
%{_includedir}/%{name}/SharedExportCore.h
%{_includedir}/%{name}/Video.h
%{_includedir}/%{name}/VideoDelegate.h

#----------------------------------------------------------------------------

%define libvlcqtqml_major 0.8
%define libvlcqtqml %mklibname vlc-qt-qml %{libvlcqtqml_major}

%package -n %{libvlcqtqml}
Summary:	A simple library to connect Qt application with libvlc (QML)
Group:		System/Libraries

%description -n %{libvlcqtqml}
VLC-Qt is a free library used to connect Qt and libvlc libraries.
It contains core classes for main media playback and also some GUI
classes for faster media player developement.

This package contains vlc-qt QML library.

%files  -n %{libvlcqtqml}
%{_libdir}/libvlc-qt-qml.so.%{libvlcqtqml_major}*

#----------------------------------------------------------------------------

%define devvlcqtqml %mklibname vlc-qt-qml -d

%package -n %{devvlcqtqml}
Summary:	Headers and development libraries for vlc-qt QML library
Group:		Development/C++
Requires:	%{libvlcqt} = %{EVRD}
Requires:	%{libvlcqtqml} = %{EVRD}
Requires:	%{devvlcqt} = %{EVRD}
Provides:	%{name}-qml-devel = %{EVRD}

%description -n %{devvlcqtqml}
Headers and development libraries for vlc-qt QML library.

%files  -n %{devvlcqtqml}
%{_libdir}/pkgconfig/libvlc-qt-qml.pc
%{_libdir}/libvlc-qt-qml.so
%{_includedir}/%{name}/QmlVideoPlayer4.h
%{_includedir}/%{name}/SharedExportQml.h

#----------------------------------------------------------------------------

%define libvlcqtwdt_major 0.8
%define libvlcqtwdt %mklibname vlc-qt-widgets %{libvlcqtwdt_major}

%package -n %{libvlcqtwdt}
Summary:	A simple library to connect Qt application with libvlc (widgets)
Group:		System/Libraries

%description -n %{libvlcqtwdt}
VLC-Qt is a free library used to connect Qt and libvlc libraries.
It contains core classes for main media playback and also some GUI
classes for faster media player developement.

This package contains vlc-qt widgets library.

%files  -n %{libvlcqtwdt}
%{_libdir}/libvlc-qt-widgets.so.%{libvlcqtwdt_major}*

#----------------------------------------------------------------------------

%define devvlcqtwdt %mklibname vlc-qt-widgets -d

%package -n %{devvlcqtwdt}
Summary:	Headers and development libraries for vlc-qt widgets library
Group:		Development/C++
Requires:	%{libvlcqt} = %{EVRD}
Requires:	%{libvlcqtwdt} = %{EVRD}
Requires:	%{devvlcqt} = %{EVRD}
Provides:	%{name}-widgets-devel = %{EVRD}

%description -n %{devvlcqtwdt}
Headers and development libraries for vlc-qt widgets library.

%files  -n %{devvlcqtwdt}
%{_libdir}/pkgconfig/libvlc-qt-widgets.pc
%{_libdir}/libvlc-qt-widgets.so
%{_includedir}/%{name}/ControlAudio.h
%{_includedir}/%{name}/ControlVideo.h
%{_includedir}/%{name}/SharedExportWidgets.h
%{_includedir}/%{name}/WidgetSeek.h
%{_includedir}/%{name}/WidgetVideo.h
%{_includedir}/%{name}/WidgetVolumeSlider.h

#----------------------------------------------------------------------------

%prep
%setup -q
%patch0 -p1
%patch1 -p1

%build
%cmake \
	-DWITH_QML:BOOL=ON \
	-DWITH_WIDGETS:BOOL=ON
# Parallel build is broken in 0.8.1
make

%install
%makeinstall_std -C build

